### PR TITLE
fixed navbar and login center

### PR DESCRIPTION
**Pull request by jemima247**
## Why / Feature

Center the login form and remove navbar before logging in

## What's Changed in the Code

Just CSS design and the nav bar component is not in layout.tsx but in the dashboard and help page.tsx

## How can I check if it works?
npm run dev

## How did I test?
Just ran it to see, the colors for light was hard to test It didn't show any changes on my computer so that might be weird

### CODE REVIEW

**Comment by Elliot-TS** [comment]
A few things weren't working properly:
- On the dashboard page, the nav bar covers part of the first budget
image
- On the budget view page, the nav bar is hidden
- On the budget view page, the add item button is white instead of purple like the add budget button on the dashboard page (makes it hard to see in light mode)
- On the login page, the login panel should have some padding so that text and buttons aren't right up against the border

**Review by Elliot-TS — CHANGES_REQUESTED** [review]
A few things weren't working properly:
- On the dashboard page, the nav bar covers part of the first budget
image
- On the budget view page, the nav bar is hidden
- On the budget view page, the add item button is white instead of purple like the add budget button on the dashboard page (makes it hard to see in light mode)
- On the login page, the login panel should have some padding so that text and buttons aren't right up against the border

**Review by Elliot-TS — CHANGES_REQUESTED** [review]
The RSO version of the dashboard and budget view are working, but the SGA versions still have problems.  On the SGA dashboard, the nav bar covers the budgets; and on the SGA budget view, the item list and sidebar covers the nav bar.

**Comment by SimonMTaye** [comment]
There's still a lot of clipping that needs to be fixed:

image

image

**Review by SimonMTaye — CHANGES_REQUESTED** [review]
Still some clipping with a bunch of the UI elements. We should probably change those before merging

image

image

**Review by SimonMTaye — APPROVED** [review]

**Pull request merged**
